### PR TITLE
Fix deploy Contract callback references

### PR DESCRIPTION
**Pull request by jmanoto**
Fixes `compiledContract` references in the deployContract callback

### CODE REVIEW

**Comment by vojdan** [comment]
@jmanoto , I get an `TypeError: compiledContract.info is undefined` if I use your fix.

**Comment by jmanoto** [comment]
That's strange.

Looking at some documentation and stepping through code locally, it appears that web3 just wraps the `web3.eth.compile.solidity()` method through to the `eth_compileSolidity` json rpc call.
https://github.com/ethereum/web3.js/blob/develop/lib/web3/methods/eth.js#L227

The JSON RPC docs for `eth_compileSolidity` don't specify that the result should have a key matching the name of the contract being compiled. See https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_compilesolidity

However the docs for web3.js seem to imply that an object with a key for the contract name is returned.
https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethcompilesolidity

Running the meteor app locally with testrpc (v2.2.3) and web3 (0.17.0-alpha) returns the following result (in screenshot) which adheres to what the JSON RPC specifies
image

Perhaps there's a version conflict somewhere? My initial thoughts are that it might be something with testrpc though I can't really find where exactly the result for `eth_compileSolidity` is constructed.

In the mean time, I've put an extra line that normalizes the return value depending if it contains a key for the `contractName`

**Comment by jmanoto** [comment]
Just noticed @naddison36 had applied the same fix and this PR may not be relevant any more.

Feel free to close.

**Comment by vojdan** [comment]
Some strange stuff going on here...
If it works in your env that's fine with me.

**Pull request merged**
